### PR TITLE
Fix issue with ImageReference id not working

### PR DESCRIPTION
**Pull request by bernardmaltais**
Creating VM from custom image does not work. The code to enable the feature was commented out.

Enabling the code is making the feature work. Not being able to create VM using custom image is a real issue with the current provider version. Hoping this can get released soon.

### CODE REVIEW

**Comment by bernardmaltais** [comment]
> Hi @bernardmaltais,
> 
> Thanks for the PR, in addition to putting the code back in could we add the tests from azurerm to confirm that it works? thanks

I am not sure how I can do this... I would need to somehow create a custom image and upload it... then deploy from it... al this dynamically... Is that what you are asking for? Never done this before and this would require to commit a multi gigabyte image to the repo... not sure this is good...

**Comment by Anakinn** [comment]
@katbyte can you please assist?

**Comment by katbyte** [comment]
@bernardmaltais , @Anakinn,

Apologies for the delay but I was on vacation and we were busy with azurerm 2.0. We test this in azurerm using a built in image:
```
storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
```

forgive my lack of knowledge with stack, but are there not pre existing images that we can use/expect to exist on a standard stack deployment?

**Comment by jbpaux** [comment]
It should work the same :)

**Comment by katbyte** [comment]
@jbpaux,

good catch! looks like i pasted the wrong bits of the azurerm config. I think we can use a data source to get an image ID for an existing one using those same properties:
```
data "azurerm_platform_image" "test" {
  location  = "%s"
  publisher = "Canonical"
  offer     = "UbuntuServer"
  sku       = "16.04-LTS"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%s"
}

resource "azurerm_managed_disk" "test" {
  name                 = "acctestd-%d"
  location             = azurerm_resource_group.test.location
  resource_group_name  = azurerm_resource_group.test.name
  os_type              = "Linux"
  create_option        = "FromImage"
  image_reference_id   = data.azurerm_platform_image.test.id
  storage_account_type = "Standard_LRS"
}
```

**Comment by jbpaux** [comment]
@bernardmaltais doesn't seem alive on this PR. @katbyte would you mind add the test so we can close it ? Or I don't know if I can contribute to this PR too.

**Comment by bernardmaltais** [comment]
> @bernardmaltais doesn't seem alive on this PR. @katbyte would you mind add the test so we can close it ? Or I don't know if I can contribute to this PR too.

This is the part I am not sure about. What kind of test? To test this you need a custom image... and I have no clue hot to turn this in a test without injecting a multi gigabyte custom image or somehow creating one to test a deploy...

If someone want to contribute a test portion you  are welcome.

**Comment by martinbjorgan** [comment]
@bernardmaltais How is it done on the azurerm provider?

**Comment by jbpaux** [comment]
> 
> 
> > @bernardmaltais doesn't seem alive on this PR. @katbyte would you mind add the test so we can close it ? Or I don't know if I can contribute to this PR too.
> 
> This is the part I am not sure about. What kind of test? To test this you need a custom image... and I have no clue hot to turn this in a test without injecting a multi gigabyte custom image or somehow creating one to test a deploy...
> 
> If someone want to contribute a test portion you are welcome.

@katbyte provided the test just above. The id is retrieved through the datasource and we deploy the resource using it.
You just need to add the test in the vm test file I guess. If you want I can add it if you give me contributor access to your repo/branch so PR can be updated with it.

**Comment by bernardmaltais** [comment]
@jbpaux Access granted ;-)

**Comment by jbpaux** [comment]
> 
> 
> @jbpaux Access granted ;-)

Ok, I'll have a look ;)

**Comment by jbpaux** [comment]
I was about to code it but isn't the test already implemented here ? 😄 
https://github.com/terraform-providers/terraform-provider-azurestack/blob/bfc4ad441f5602b9bc7ddd19d655dce5741b29e8/azurestack/resource_arm_managed_disk_test.go#L381

**Comment by katbyte** [comment]
@jbpaux,

that test is for the managed disk, you'll need to take that and instead use a vm resource with the storage image reference:
```
data "azurerm_platform_image" "test" {
  location  = "%s"
  publisher = "Canonical"
  offer     = "UbuntuServer"
  sku       = "16.04-LTS"
}

resource "azurerm_virtual_machine" "test" {
  name                  = "acctvm"
  location              = azurerm_resource_group.test.location
  resource_group_name   = azurerm_resource_group.test.name
  network_interface_ids = [azurerm_network_interface.test.id]
  vm_size               = "Standard_D1_v2"

  storage_image_reference {
    id = azurerm_image.testdestination.id
  }

  storage_os_disk {
    name          = "myosdisk1"
    caching       = "ReadWrite"
    create_option = "FromImage"
  }

  os_profile {
    computer_name  = "mdimagetestsource"
    admin_username = "%s"
    admin_password = "%s"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  tags = {
    environment = "Dev"
    cost-center = "Ops"
  }
}

**Comment by manicminer** [comment]
@bernardmaltais @jbpaux I've taken a look at this but have been unable to get it to work. When testing, specifying the id of a platform image returns the following error when creating the VM:

```
Id /Subscriptions/11111111-2222-3333-4444-555555555555/Providers/Microsoft.Compute/Locations/mylocation/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.20180911 is not a valid resource reference.
```

or for a RedHat image
```
Id /Subscriptions/11111111-2222-3333-4444-555555555555/Providers/Microsoft.Compute/Locations/mylocation/Publishers/RedHat/ArtifactTypes/VMImage/Offers/RHEL/Skus/7-RAW/Versions/7.6.0 is not a valid resource reference.
```

Is anyone else able to test this on their Stack environment?

**Comment by Anakinn** [comment]
@manicminer I think you are missing a point. This is meant to be used with custom image. I am using it for over a year and it is working fine. You need to specify custom image like this: /subscriptions/subscription_id/resourceGroups/rg-Name/providers/Microsoft.Compute/images/Imagename and you need to have custom image created and uploaded to azure stack.  To create VM from predefined images is working as expected without specifying image itself.

**Pull request closed without merging**
