### PR TITLE
Removed unsupported parameters in network security rule resource/datasource

### PR DESCRIPTION
**Pull request by coderGo93**
- Removed two unsupported parameters and its tests that uses it in resource/datasource of `azurestack_network_security_rule`.

### CODE REVIEW

**Comment by katbyte** [comment]
Same here, any documention on these not being supported or not in azure stack?

**Comment by coderGo93** [comment]
> Same here, any documention on these not being supported or not in azure stack?

Hi @katbyte , here the doc https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-2108 , it mentions that `Application Security Groups` is not yet supported in Azure Stack Hub

**Comment by coderGo93** [comment]
> Ahh ok, we'll need to remove these as they were not in the 0.10 release and shouldn't go out with 1.0 then: image
> 
> i'll merge the other PR and this one when its been updated to remove them

Understood, I will remove those files in this same PR. Thank you

**Comment by coderGo93** [comment]
@katbyte is ready to review again, for some reason it doesn't appear anymore your github name in `Reviewers`

**Review by katbyte — APPROVED** [review]
LGTM 🖍️

**Pull request merged**
