### PR TITLE
Add additional resources to Azure Stack Hub

### PR DESCRIPTION
**Pull request by rna-afk**
This will add the azurestack_storage_account_sas, azurestack_image, azurestack_subnet_network_security_group_association and the azurestack_dns_cname_record.

### CODE REVIEW

**Comment by patrickdillon** [comment]
These are resources we are adding in our fork which we are using for installing OpenShift on Azure Stack. It would be great to get some expert feedback and we would like to merge these upstream.

**Comment by mzakharoff** [comment]
I could really use this PR as well.

**Comment by katbyte** [comment]
Hey @rna-afk - Sorry its taken so long to get back to you here.

For a while now we've been without access to a stack environment to test either PRs or the provider, so this project had been sidelined for some time. However that has finally changed! and we intend to pick it back up and put it back into active development.

The first step in doing so is to upgrade the tooling and techniques used to match what we do in AzureRM and AzureAD, which I'm doing right now so other engineers can get started ASAP. This will unfortunate break this PR 🙁 Hopefully we'll pick it up and get these changes/features merged during the upcoming dev cycle (upwards of 2-3 months). But if at any time these merge conflicts are fixed up I'll be happy to review/test/merge it, thou understand it has been quite some time so don't expect you to. I'll only close it out once we've addressed the issued within.

Again - thank you for your patience with us resolving our testing environment and contributions here

@mzakharoff @sdodson @patrickdillon for visibility

**Comment by patrickdillon** [comment]
cc @staebler

**Comment by staebler** [comment]
> we intend to pick it back up and put it back into active development.

That is wonderful news!

**Comment by katbyte** [comment]
@rna-afk - i'm going to close this as a couple of these resources have already been added so this PR is out of date now, and others are covered by open PRs.

**Comment by staebler** [comment]
> @rna-afk - i'm going to close this as a couple of these resources have already been added so this PR is out of date now, and others are covered by open PRs.

Thanks, @katbyte. It is lovely to see some fresh activity in this repo.

**Pull request closed without merging**
